### ISSUE TITLE
Time and date

### ISSUE THREAD

**Issue by michaeldouble07** [Esri/large-network-analysis-tools#17]
Hi, is there a way to put in time_of_day or some kind of day and time for the origins? Such as a Wednesday at 8 pm, or using Unix time converted to milliseconds?

**Comment by mmorang** [comment]
Yes, definitely.  You can set the time of day for the OD Cost Matrix, which will be interpreted as the start time for all origins.

If you just want to hard-code something for your specific analysis, you can change it in the od_config.py file:
![image](https://user-images.githubusercontent.com/14127094/160454306-d7482773-9cb6-42b0-9fff-9e02e9c8ed70.png)

Use a `datetime.datetime()`.  You can set a specific date, or you can specify a generic weekday or "today."  For one of these generic weekdays, you have to use our special reserved dates in 1899/1900.  I just noticed that those are not documented in the solver object documentation (something I will fix for the next release), but the list of those dates is included in the [Make OD Cost Matrix Analysis Layer documentation](https://pro.arcgis.com/en/pro-app/latest/tool-reference/network-analyst/make-od-cost-matrix-analysis-layer.htm#GUID-4339881E-980F-4449-9233-C01006DF08E1) for the `time_of_day` parameter and is the same.
![image](https://user-images.githubusercontent.com/14127094/160455092-28266edb-8d2e-489b-9e52-1f6e7da6f948.png)

If you want to make it a user parameter, you will need to add a parameter to the script tool definition and pass it all the way through the stack like how it's already done for travel mode, cutoff, and number of destinations to find.

Setting a time of day will not have an impact on the OD Cost Matrix results unless the impedance attribute being used has some time-dependent properties, for example, if you're using traffic or public transit data.

**Comment by michaeldouble07** [comment]
Thanks for the info, but is it possible for you to add this feature, so that we can change the time with the tool?  I would be using this for using the traffic data, that is why I would need it.  I would greatly appreciate if you could add this change.  I have no experience with creating tool's, that is why I am asking.

**Comment by mmorang** [comment]
I'll see what I can do.

**Comment by mmorang** [comment]
Okay, the tool code has been updated to expose time of day as a user parameter.  You can download the update from https://github.com/Esri/large-network-analysis-tools/releases/ or clone the repo.
