### ISSUE TITLE
Curb approach

### ISSUE THREAD

**Issue by michaeldouble07** [Esri/large-network-analysis-tools#20]
Is it possible to get curb approach added as a feature to this tool?  I would like to set the curb approach for everything to the right hand side of the vehicle.  I understand that I would have to do something with field mappings, but I am unsure how to do that.

**Comment by mmorang** [comment]
You can use curb approach with the tool as is.

Just add a field called CurbApproach to your input origins and destinations and populate it with values according to those described [in the documentation](https://pro.arcgis.com/en/pro-app/latest/arcpy/network-analyst/origindestinationcostmatrix-input-data-types.htm) (a value of 1 for right side of vehicle).  The tool already automatically maps any input fields with names matching those in the OD Cost Matrix input table schemas.

Please give that a try and let me know if it works.

**Comment by michaeldouble07** [comment]
This feature works, thank you for showing me how to do this.

**Comment by michaeldouble07** [comment]
Curb approach works, but in the end, we don’t think that this tool is effective for our needs, as it still seems too slow.  I know this is the problem with using vrp, and I am doing too small of a pair in order to obtain the benefits this tool has to offer.  I liked the idea, but I think since my matrices are so small that I will have to go with the regular of matrix tool you made.  Do you have any suggestion for a way to efficiently obtain travel times quickly?  The reason I ask is when I use the large of matrix tool, I do about a 100x100 matrix and filter it down to about 4% of the travel times.

**Comment by MarcusBlake-UC** [comment]
You might find the Pandana python library quicker for basic shortest time/distance work...but it is not as sophisticated as Esri's networking tools 

https://udst.github.io/pandana/

**Comment by michaeldouble07** [comment]
This looks great, but I bought street map premium to get fast offline travel times, as the rest api was slow.  I need to use arcgis.  I have arcgis pro with network analyst and street map premium.  Based on this, what would you suggest?

**Comment by mmorang** [comment]
Hello @michaeldouble07.  I'm afraid I don't really know what you're trying to do, so it's hard for me to advise on what approach to take.  You've confused me with your mention of VRP.  Can you describe the goal of your project and what requirements you have?

Regarding Pandana, you can actually create a Pandana network from a network dataset using the [arcpy NetworkDataset class](https://pro.arcgis.com/en/pro-app/latest/arcpy/network-analyst/networkdataset.htm), with its edge and junction cursors.  I think it will be difficult to model all the nuances included in the network dataset, like turns, but you can set the travel mode and time of day, and it will return impedances and restrictions consistent with those.  So, you could build a Pandana network modeling that specific time of day and travel mode.

I think Pandana networks are stored in memory (if they behave somewhat like networkx, which I think they do), so you will not be able to easily store an entire Streetmap Premium for a whole continent.  But you can specify an extent or polygon for your study area and only extract the portion of the network you need.

I'm not as familiar with Pandana, but I know the [networkx ](https://networkx.org/) module has a ton of options for graph searches.  This is what I usually recommend for users who want to do some sort of network-based calculations not covered by the solvers available in Network Analyst.  But, it sounds like your issue isn't that you want some exotic algorithm but that you need better performance.

Please do let me know more about what you're trying to do, and we'll see if we can come up with something.

Also, just to check, are you using Pro 2.9 or higher?  We made some substantial performance improvements for OD Cost Matrix in 2.9. Solving is about 20-70% faster, depending on the analysis parameters.
