### ISSUE TITLE
Known pairs issues/questions

### ISSUE THREAD

**Issue by michaeldouble07** [Esri/large-network-analysis-tools#22]
I am using the known pairs tool, and I noticed that when I put in 1/3/1990 7:20:00 AM I got 6/8/2022 7:20 AM showing in the results.  Is there something I am doing wrong?  My goal is to get the traffic time for a Wednesday at 7:20:00 AM.  I am also having an issue as how to set curb approach for the known pairs tool, any guidance would be helpful, to get that to work.  I have been comparing the times between the known pairs tool and the large of cost matrix, and they are not turning out the same, I suspect that they may be cause by the issues described above.

**Comment by michaeldouble07** [comment]
Hello @mmorang 

I need the curb approach feature, by the end of the week or beginning of next week. One thing I would like to clarify is that if I use the known pairs tool I should get the same results a as the large is matrix, is this correct?  I also had a bit of trouble when I created the feature class and tried to do point calculations on the fly when adding to the feature class, it did not work with the known pairs tool, but it works for the large of matrix tool, so for the known pairs tool I had to make a table and then use table to point, and that worked for the known pairs tool.  Could you please explain a valid config to create a feature class that would work with the known pairs tool.

**Comment by mmorang** [comment]
That code looks generally fine.  Did the resulting feature class look okay?  All the points displayed in the map in the right places and it had the desired fields?

When you say "The known pairs tool does not like it with this feature class configuration," what do you mean?  Did the tool throw an error message, and what was the message?  I don't have enough information to diagnose that part of the problem.

**Comment by mmorang** [comment]
Hello @michaeldouble07.  Were you able to successfully use your CurbApproach fields with my updated tool?  I'd like to eventually merge this branch into the master branch, but I wanted to make sure it had worked correctly for you before I proceed.

**Comment by mmorang** [comment]
I haven't heard back from you, but I wanted to close out this project, so I went ahead and merged my changes.  If you have CurbApproach in your input data, this should be used in the analysis successfully now.

If you're still having trouble with the other problem, please let me know.  I'm happy to help.  If I haven't heard back from you after some period of time, I'll close this issue as resolved.

**Comment by michaeldouble07** [comment]
Sorry, I have been dealing with other stuff, and I will make sure to test it this weekend.  I will let you know if I have issues, Thank you for the support.

**Comment by mmorang** [comment]
I'm going to assume that you resolved your issue and that my updates to the tool to transfer usable input fields worked, so I'll close this issue.  Feel free to reopen if you're still having trouble.
