### ISSUE TITLE
Solve Large Analysis with known OD Pairs tool fails

### ISSUE THREAD

**Issue by gboura** [Esri/large-network-analysis-tools#23]
I have been trying to use the tool within ArcGIS Pro, with a GTFS network dataset that I have developed. However, when running the tool, it fails and I get the following message in Pro:

> File "C:\Users\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\concurrent\futures\process.py", line 239, in _process_worker

I have double-checked the data, and they don't appear to have any issue. Note that I have also performed route analysis using the same data and network dataset successfully. 

I am not sure what the above message means. Any advice?

Thanks!

**Comment by mmorang** [comment]
Hello @gboura. I presume you are the same user from this Esri Community thread: https://community.esri.com/t5/arcgis-network-analyst-questions/large-network-analysis-toolbox-for-network/m-p/1183690.  Just wanted to link to that other thread for broader context.

I can't really determine what the problem might be from that one line of text above.  Basically the tool uses the concurrent.futures module to spin up parallel processes, and what you've pasted above is a partial error message indicating that some sort of problem with the parallelization occurred.  It could be that you set the max parallel processes too high, or it could be some other weird issue.

Can you give me more details about what's going on?

First, please paste the entire error message text.  (Try switching to the "Messages" section in the little box that shows the tool parameters and messages.  Copy and paste the entire thing in here.)

Second, what do your inputs look like?  What values have you used for the input parameters, how many origins and destinations do you have, etc.?

**Comment by mmorang** [comment]
Hello @gboura.  In my latest update to the tool code (from earlier today), I made a small change that should improve error messages when the parallelization subprocess encounters a problem.  If you're still using this script and having problems with it, you can try the latest update, and hopefully it will at least give you a better message indicating what the problem is.

**Comment by mmorang** [comment]
If you're still experiencing this problem, please reopen this issue with more details about your error after retrying with the updated tool.
